version: '3.3'

services:
  nginx:
    container_name: linky-api-nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - app
    ports:
      - "8084:80"
  app:
    build: .
    container_name: linky-api
    restart: always
    env_file:
      - .env
    volumes:
      - ./runtime:/app/runtime
      - .env:/app/.env